---
title: "p8105_hw5_ec3342"
author: "Ekta Chaudhary"
date: "04/11/2019"
output: github_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo  = TRUE)
library(tidyverse)
library(rvest)
library(purrr)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
```
# Question 1

#The code chunk below loads the iris dataset from the tidyverse package and introduces some missing values in each column. The purpose of this problem is to fill in those missing values.

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```
```{r}
rpl_miss = function(x) {
if (is.numeric(x))
  { 
  x = replace_na(x, mean(x, na.rm = TRUE)) #Using a function to replace the missing values of numeric variables with the mean of non-missing values
  }
else if (is.character(x)) {
x = replace_na(x,"virginica")} #Using a function to replace the missing values of character variables, with "virginica"
  }
iris_new = map(iris_with_missing, rpl_miss) %>% 
as_tibble() #Applying the function to the columns of iris_with_missing using a map statement.

```

# Question 2

#Creating a tidy dataframe containing data from all participants, including the subject ID, arm, and observations over time:

```{r}
file_name = list.files("./data")

read_csv_files = 
  function(file_name) {
    subject_data = read_csv(
      file = str_c("./data/", file_name)
      ) %>%
      mutate(
        file = file_name
      )
    }
subject_data = map_df(
  file_name, read_csv_files
) %>%
pivot_longer(
  week_1:week_8, names_to = "week",
  values_to = "measurement"
  ) %>%
  separate(
    file, into = c("group","subject",sep = "-")
    ) %>%
  mutate(
    group = recode(group,"con" = "control","exp" = "experimental")
    ) %>%
  select(group,subject,week,measurement)
```


```{r}
subject_data %>%
  ggplot(aes(x = week, y = measurement, group = subject, color = subject)) + 
  geom_line() +
  facet_grid(~group) + 
  labs(
    x = "Week",
    y = "Observation"
  ) + 
  theme(
    legend.position = "bottom"
  ) + viridis::scale_color_viridis(
    name = "Subject ID",
    discrete = TRUE
  )
  
```


